const dict = [
  ['what do you', 'wha-r-yah'],
  ['what do you', 'whatchah'],
  ["i'm going to", 'ahmma'],
  ["i'm gonna", 'ahmma'],
  // ['the ', 'dâh '],
  // ['you', 'yah'],
  ['what you', 'wha-tchu-yah'],
  ['t to', "'râh"],
  ['t do', 'tchâh'],

  ["don't", 'ron'],
  ['got to', 'garâh'],
  ['i am', 'amm'],
  ["i'm", 'amm'],
  ['i will', 'auh'],
  ["i'll", 'auh'],
  ['d l', 'dl'],
  ['t you', 'tchyah'],
  ['lot of s', 'loras'],
  ["should've", 'shulrah'],
  ['should have', 'shulrah'],
  ["could've", 'kurah'],
  ['which is', 'wichis'],
  ['could have', 'kurah'],
  ["would've", 'wurah'][('would have', 'wurah')],
  ["it's the", "it'sâh"],
  ['it is the', "it'sâh"],
  ['let just', 'letjust'],
  ['and also', 'enolsol'],
  ['and i also', 'enaolsol'],
  ['does that', 'zat'],
  ['does this', 'dâzes'],
  ['does this have', 'dâzêsave'],
  ['as him', 'asim'],
  ['of what', 'ovuat'],
  ['of', 'ov'],
  ['as well as', 'as wellas'],
  ['if all goes well', 'ifal goesuell'],
  ['in our', 'inour'],
  ['trying to', 'truiaida '],
  ['taking to', 'teikinda'],
  ['get to', 'getâ'],
  ['it has', 'idas'],
  ['to that', 'râ that'],
  ['can i', 'canai'],
  ['i want you to', 'iuan tchê rê'],
  ["think i'm", 'thinkM'],
  ['heard anything', 'heardything'],
  ["there's a", 'reza'],
  ['With an accident', 'withanAccident'],
  ['why would they', 'ua rdey'],
  ['how would i', 'rauurai'],
  ['would he', 'uâre'],
  ["and I'd always", 'anai-rolways'],
  ["and it'll", "anir'll"],
  ['and this', 'anis'],
  ["why he's so", 'whaiSS so'],
  ['an example', 'anexample'],
  ["and that's", 'anets'],
  ['on that', 'onet'],
  ['getting that', 'geinat'],
  ['saying that', 'sayinat'],
  ['ing', 'in'],
  ['there is', 'theris'],
  ['watching a', 'watchina'],
  ['wish i', 'wishai'],
  ['with all', 'withou'],
  ['did i ever tell you', 'dirai ever tellyou'],
  ["How'd you", 'howdju'],
  ['about anything', 'abouranything'],
  ["l'm actually", "i'machually"],
  ['go together', 'gorogether'],
  ['if he', 'ife'],
  ['build her', 'builder'],
  ['Maybe he', 'maybe i '],
  ['died in there', 'dairiner'],
  ['them all', 'temou'],
  ['something in the', 'sometinina'],
  ['that in', 'tharin'],
  ['that is', 'thadis'],
  ['n you', 'nyou'],
  ['with this', 'withis'],
  ['should we', 'shou-we'],
  ['and i', 'enai'],
  ['n the', 'nnah'],
  ['have to', 'hafta'],
  ['t are you', 'tcha'],
  ['cause s', 'causs'],
  // ['where are you', 'whereya'],
  ['nt o', 'no'],
  [' them', " ' em"],
  [' him', ' im'],
  [' his', ' im'],
  [' her', ' er'],
  [' he', ' e'],
  [' she', ' e'],
  ['n th', 'n'],

  ['k o', 'ko'],
  ['k a', 'ka'],
  ['p o', 'po'],
  ['t i', 'di'],
  ['d i', 'rai'],
  ['n one', 'nuone'],
  ['s a', 'sa'],
  ['s o', 'so'],
  ['s i', 'si'],
  ['p a', 'pa'],
  // ['d ', ''],
  ['t ', ''],
  ['n o', 'no'],
  ['n e', 'ne'],
  ['n a', 'na'],
  ['ne o', 'no'],
  ['d a', 'da'],
  ['t l ', 'tl'],
  ['t a', 't-a'],
  ['m i', 'mi'],
]

const frase = `
but it was time
`
// by then and I went on the

const newFrase = dict.reduce(
  (acc, curr) => (curr ? acc.replace(new RegExp(curr[0], 'gi'), curr[1]) : acc),
  frase
)

console.log(newFrase)
